### ISSUE TITLE
Does tab activate?

### ISSUE THREAD

**Issue by jamischarles** [extrabacon/atom-turbo-javascript#3]
Not sure how to activate these...

For console log I assume I type
`cl:` and then tab?

That isn't working. Sorry, maybe it's obvious. Just isn't working for me.

**Comment by ghost** [comment]
I had to restart Atom to get it to work.  It was kind of confusing because the atom package has snippets as well.  So I installed this one, and some snippets worked, but they were just the standard atom JS snippets.  To get these ones to work I had to restart it.

**Comment by bermudalocket** [comment]
Just a comment to note this is still an issue. It might be helpful to instruct the user to restart the IDE after installing this plugin. I was ready to give up and uninstall before I found this. It's funny, I had the same exact confusion as @turbobuilt did: some were working, some not. I however did not know they were standard Atom snippets... so that clears up that mystery for me.
